CREATE TABLE COURSE
(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STUDENT
(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    PRIMARY KEY (ID)
);