create table users
(
    id  int,
    name   varchar(32)
);

create table employee
(
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   varchar(32),
    salary integer,
    password varchar(200),
    role varchar(20)
);